### PR TITLE
Upgrade to sbt 0.13.5 version + syntax + the latest plugins

### PR DESCRIPTION
**Pull request by jaceklaskowski**

### CODE REVIEW

**Comment by benmccann** [comment]
@jaceklaskowski just a reminder that there's a merge conflict still

**Comment by benmccann** [comment]
I made a new version of this PR that doesn't have merge conflicts and makes the plugin an AutoPlugin https://github.com/typesafehub/sbteclipse/pull/236

**Comment by jaceklaskowski** [comment]
Thanks @benmccann!

**Comment by jsuereth** [comment]
Thanks @benmccann closing this in favor of your PR.

**Pull request closed without merging**
