### PR TITLE
Don't fill Eclipse project with a ton of empty directories when adding managed directories to classpath

### PR DESCRIPTION
**Pull request by benmccann**
Thanks to @oleastre for tracking down this problem in https://github.com/playframework/playframework/pull/4074#issuecomment-78450169

Also fixes the issue reported in https://github.com/typesafehub/sbteclipse/issues/99

### CODE REVIEW

**Comment by dragos** [comment]
LGTM

**Comment by dragos** [comment]
My only concern is what happens if it's an all-fresh Sbt project. Then none of `src/main` or `src/test` will exist, right? So Eclipse won't have any configured source directories...

**Comment by benmccann** [comment]
If you create the project using activator or from another template then you will have `src/main` and `src/test` which is probably the best way to handle and what we recommend most often. I'm not sure sbteclipse's job is to create a template project. It's probably better if it just does one thing and reflects what you have already.

**Comment by dragos** [comment]
Well, in that case one other answer is that `sbteclipse` should just do what it does: reflect exactly what Sbt knows about source directories. If you don't need some source directory, remove that from your build definition. :)

I don't feel like arguing too much, I'm fine with this change as is

**Comment by benmccann** [comment]
Thanks!!

**Pull request merged**
