### PR TITLE
Execute preTasks before calculating externalDependencies

### PR DESCRIPTION
**Pull request by mkurz**
Makes sure all compiled files and folders exist already.

When a Play Framework project has **no** `target` folder yet (because the project wasn't compiled yet) and run `sbt eclipse` on such a not-yet-compiled and not-yet-eclipsified Play project the `target/scala-2.11/classes_managed` folder won't get added to the `.classpath` file (despite it gets created on the filesystem eventually) - which results in a lot of errors when importing the project in eclipse.

That's because right now we add managedClassDirectory folders to the `.classpath` file [**only if the folder does exists on the filesystem**](https://github.com/typesafehub/sbteclipse/blob/v5.0.1/src/main/scala/com/typesafe/sbteclipse/core/Eclipse.scala#L500) - but because the compilation from `preTasks` hasn't been done yet the folder isn't there yet. 

**Most users won't recognize this bug because they probably run `sbt eclipse` _after_ they already compiled their project at least once - having therefore created the `target/scala-2.11/classes_managed` folder on the filesystem already.**

### CODE REVIEW

**Comment by mkurz** [comment]
@benmccann If you could release new version `5.0.2` after merging this that would be great. Thank you!

**Comment by mkurz** [comment]
@benmccann if you could release a new version that whould be great!

**Comment by benmccann** [comment]
5.1.0 should be released now!

Would you be able to return the favor for me? :-)  I'm looking to get my two pending PRs merged at https://github.com/typesafehub/js-engine/pulls

**Comment by mkurz** [comment]
Thanks Ben!
Unfortunately I don't have commit rights for the `js-engine`repo...

**Comment by mkurz** [comment]
You probably want to ping James, Rich, Greg or Christopher Hunt

**Comment by benmccann** [comment]
Ok, thanks!

**Pull request merged**
