### PR TITLE
replace hard-coded default "bin" output directory with eclipseOutput setting, if defined

### PR DESCRIPTION
**Pull request by philwalk**
The purpose is to use the `eclipseOutput` setting, if defined, when generating the following entry of the generated .classpath file (as it would look if `eclipseOutput` is set to "eclipse-bin"):
```
<classpathentry kind="output" path="eclipse-bin"/>
```

Currently, this entry always looks like this:
```
<classpathentry kind="output" path="bin"/>
```

Wow, I dont think I created this PR correctly, based on the result.
Ahh, I see that I accidentally selected the wrong target branch.   Not sure how to proceed from here, It would be nice if we could close or delete this PR, although I don't know how to do so.

### CODE REVIEW

**Comment by benmccann** [comment]
You can click "Edit" in the top right to change the branch

You can click "Close" at bottom of this page to close the PR (though hopefully you can edit the branch and that will fix it and make it unnecessary to close)

**Comment by philwalk** [comment]
The code I'd like to merge is in my fork at https://github.com/philwalk/sbteclipse.git
Is there any way to fix this PR to pull those changes?   If not,  I'll close this one, although I'm not confident I understand how to create the PR, so I'll have to study it for a bit.   Thanks for the feedback, and sorry for the noise.

**Comment by benmccann** [comment]
You pushed your changes to your master branch. Generally you should create a new branch for each PR.

I would recommend the following:
```
git reset HEAD~1 (undo your last commit)
git push -f (force push to github to undo last commit there)
git checkout -b eclipseOutput (create a new branch named eclipseOutput)
git commit -am "extended scope of eclipseOutput setting to cover eclipse classes bin directory"
git push
```

The `git push` command might be a bit different for you. My `~/.gitconfig` has a couple lines that I think make it easier:
```
[push]
	default = current
```

Once you've gotten the branch pushed, wait 2-3 seconds and a message will appear on both https://github.com/philwalk/sbteclipse and https://github.com/typesafehub/sbteclipse asking if you want to create a new pull request with your changes

**Comment by philwalk** [comment]
This was created in error, thanks for the assistance in creating the correct PR.

**Pull request closed without merging**
